// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGameByIDHandlerFunc turns a function with the right signature into a get game by Id handler
type GetGameByIDHandlerFunc func(GetGameByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGameByIDHandlerFunc) Handle(params GetGameByIDParams) middleware.Responder {
	return fn(params)
}

// GetGameByIDHandler interface for that can handle valid get game by Id params
type GetGameByIDHandler interface {
	Handle(GetGameByIDParams) middleware.Responder
}

// NewGetGameByID creates a new http.Handler for the get game by Id operation
func NewGetGameByID(ctx *middleware.Context, handler GetGameByIDHandler) *GetGameByID {
	return &GetGameByID{Context: ctx, Handler: handler}
}

/*
	GetGameByID swagger:route GET /games/{gameId} getGameById

Get a game by ID
*/
type GetGameByID struct {
	Context *middleware.Context
	Handler GetGameByIDHandler
}

func (o *GetGameByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGameByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
