// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"novelgo/internal/pkg/models"
)

// UpdateGameOKCode is the HTTP code returned for type UpdateGameOK
const UpdateGameOKCode int = 200

/*
UpdateGameOK Game updated

swagger:response updateGameOK
*/
type UpdateGameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Game `json:"body,omitempty"`
}

// NewUpdateGameOK creates UpdateGameOK with default headers values
func NewUpdateGameOK() *UpdateGameOK {

	return &UpdateGameOK{}
}

// WithPayload adds the payload to the update game o k response
func (o *UpdateGameOK) WithPayload(payload *models.Game) *UpdateGameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update game o k response
func (o *UpdateGameOK) SetPayload(payload *models.Game) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateGameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateGameNotFoundCode is the HTTP code returned for type UpdateGameNotFound
const UpdateGameNotFoundCode int = 404

/*
UpdateGameNotFound Game not found

swagger:response updateGameNotFound
*/
type UpdateGameNotFound struct {
}

// NewUpdateGameNotFound creates UpdateGameNotFound with default headers values
func NewUpdateGameNotFound() *UpdateGameNotFound {

	return &UpdateGameNotFound{}
}

// WriteResponse to the client
func (o *UpdateGameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
