// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteGameNoContentCode is the HTTP code returned for type DeleteGameNoContent
const DeleteGameNoContentCode int = 204

/*
DeleteGameNoContent Game deleted

swagger:response deleteGameNoContent
*/
type DeleteGameNoContent struct {
}

// NewDeleteGameNoContent creates DeleteGameNoContent with default headers values
func NewDeleteGameNoContent() *DeleteGameNoContent {

	return &DeleteGameNoContent{}
}

// WriteResponse to the client
func (o *DeleteGameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteGameNotFoundCode is the HTTP code returned for type DeleteGameNotFound
const DeleteGameNotFoundCode int = 404

/*
DeleteGameNotFound Game not found

swagger:response deleteGameNotFound
*/
type DeleteGameNotFound struct {
}

// NewDeleteGameNotFound creates DeleteGameNotFound with default headers values
func NewDeleteGameNotFound() *DeleteGameNotFound {

	return &DeleteGameNotFound{}
}

// WriteResponse to the client
func (o *DeleteGameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
