// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"novelgo/cmd/httpserver/models"
)

// GetGameByIDOKCode is the HTTP code returned for type GetGameByIDOK
const GetGameByIDOKCode int = 200

/*
GetGameByIDOK Game details

swagger:response getGameByIdOK
*/
type GetGameByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Game `json:"body,omitempty"`
}

// NewGetGameByIDOK creates GetGameByIDOK with default headers values
func NewGetGameByIDOK() *GetGameByIDOK {

	return &GetGameByIDOK{}
}

// WithPayload adds the payload to the get game by Id o k response
func (o *GetGameByIDOK) WithPayload(payload *models.Game) *GetGameByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get game by Id o k response
func (o *GetGameByIDOK) SetPayload(payload *models.Game) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGameByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGameByIDNotFoundCode is the HTTP code returned for type GetGameByIDNotFound
const GetGameByIDNotFoundCode int = 404

/*
GetGameByIDNotFound Game not found

swagger:response getGameByIdNotFound
*/
type GetGameByIDNotFound struct {
}

// NewGetGameByIDNotFound creates GetGameByIDNotFound with default headers values
func NewGetGameByIDNotFound() *GetGameByIDNotFound {

	return &GetGameByIDNotFound{}
}

// WriteResponse to the client
func (o *GetGameByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
