// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListGamesHandlerFunc turns a function with the right signature into a list games handler
type ListGamesHandlerFunc func(ListGamesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListGamesHandlerFunc) Handle(params ListGamesParams) middleware.Responder {
	return fn(params)
}

// ListGamesHandler interface for that can handle valid list games params
type ListGamesHandler interface {
	Handle(ListGamesParams) middleware.Responder
}

// NewListGames creates a new http.Handler for the list games operation
func NewListGames(ctx *middleware.Context, handler ListGamesHandler) *ListGames {
	return &ListGames{Context: ctx, Handler: handler}
}

/*
	ListGames swagger:route GET /games listGames

List all games
*/
type ListGames struct {
	Context *middleware.Context
	Handler ListGamesHandler
}

func (o *ListGames) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListGamesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
