name: Build Client

on:
  pull_request:
    types: [labeled]
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-create-pull-request:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/novelgo-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build artifact
      run: npm run build

    - name: Clone target repository
      run: |
        git clone https://github.com/fanzeng/fanzengau.com.git

    - name: Commit and push changes
      run: |
        cd fanzengau.com
        git checkout master
        git checkout -b update-holdem-client
        cp -r ../dist/* submodules/novelgo/
        git config --global user.email "fanzengau@gmail.com"
        git config --global user.name "Fan Zeng"
        git add submodules/novelgo
        git commit -m "Update novelgo client build"
        git push https://x-access-token:${{ secrets.CLIENT_PR_GH_TOK }}@github.com/fanzeng/fanzengau.com.git update-novelgo-client

    - name: Clean up
      run: rm -rf fanzengau.com
