name: Build Docker

on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build Docker image
        working-directory: ./server/novelgo
        run: docker build -t fanzengau/novelgo-app:latest .
      - name: Push Docker image
        working-directory: ./server/novelgo
        run: docker push fanzengau/novelgo-app:latest
